### ISSUE TITLE
copy&paste feature stops working in version 5.0 onwards

### ISSUE THREAD

**Issue by rbatllet** [nikku/bpmn-js-native-copy-paste#2]
What are the changes that would have to be made for the copy & paste functionality to continue working from version 5.0 onwards?

Thanks in advance

**Comment by nikku** [comment]
We've identified the bug and are working on a fix.

**Comment by rbatllet** [comment]
I am very happy to hear that a solution is about to be released. For a moment I had thought that the API had been changed.

**Comment by nikku** [comment]
There were a couple of regressions in our copy and paste implementation, including `processRef` not being copied anymore: https://github.com/bpmn-io/bpmn-js/pull/1707.

This will soon be released in bpmn-js.

**Comment by rbatllet** [comment]
Good to know. Thank you very much for everything.

**Comment by nikku** [comment]
Closing this issue as it will work again with the soon to be released `bpmn-js@9.4`.

You can already try it out locally on this example.
